export const ja = {
  nav: {
    dashboard: "ダッシュボード",
    analytics: "分析",
    projects: "プロジェクト",
    clients: "クライアント",
    tasks: "タスク",
    workflows: "ワークフロー",
    artifacts: "成果物",
    agents: "AIエージェント",
    approvals: "承認",
    validation: "検証",
    settings: "設定",
  },
  common: {
    back: "戻る",
    create: "作成",
    save: "保存",
    cancel: "キャンセル",
    loading: "処理中...",
    unassigned: "未割当",
    noData: "データがありません",
    openList: "一覧へ",
    project: "プロジェクト",
    workflow: "ワークフロー",
    task: "タスク",
    progress: "進捗",
    tasksDone: "件完了",
    updated: "更新",
    tasks: "タスク",
    comms: "連絡",
    projects: "案件",
  },
  workflow: {
    title: "ワークフロー",
    controls: "ワークフロー操作",
    controlsDesc: "秘書AI経由でエージェントを順番に実行",
    start: "ワークフロー開始",
    executeNext: "次のタスクを実行",
    startAndExecute: "開始して最初のタスクを実行",
    openWorkflow: "ワークフローを開く",
    noTasks: "タスクがありません",
    structure: "ワークフロー基本構造の可視化",
    automation: "自動化対応",
    workflowCount: "件のワークフロー",
  },
  approval: {
    title: "承認",
    subtitle: "Human in the Loop 承認管理",
    pending: "承認待ち",
    history: "履歴",
    noPending: "承認待ちはありません",
    approve: "承認する",
    reject: "却下する",
    commentPlaceholder: "コメント（任意）",
    goToList: "承認一覧へ",
  },
  client: {
    title: "クライアント",
    subtitle: "リード・クライアント管理と連絡履歴",
    leads: "リード",
    activeClients: "契約中クライアント",
    add: "クライアント追加",
    addAsLead: "リードとして追加",
    noClients: "クライアントがありません",
    activate: "クライアントを有効化する",
    namePlaceholder: "名前 *",
    companyPlaceholder: "会社名",
    emailPlaceholder: "メール",
    subjectPlaceholder: "件名",
    contentPlaceholder: "内容 *",
    businessProject: "ビジネス案件作成",
    businessProjectDesc: "営業 → 契約 → 納品のビジネスワークフローを開始",
    createBusinessProject: "ビジネス案件を作成",
    communications: "連絡履歴",
    addCommunication: "履歴を追加",
    noCommunications: "履歴なし",
    relatedProjects: "関連プロジェクト",
    projectName: "案件名",
    projectDesc: "案件概要",
  },
  project: {
    title: "プロジェクト",
    subtitle: "案件の作成と管理",
    new: "新規プロジェクト",
    namePlaceholder: "プロジェクト名",
    descPlaceholder: "説明（任意）",
    addTask: "タスク追加",
    taskName: "タスク名",
    taskCreate: "タスク作成",
    descLabel: "説明",
    workflowStructure: "基本構造（ステージ / タスク）",
  },
  task: {
    title: "タスク",
    subtitle: "タスク一覧と作成",
    add: "タスク追加",
    noTasks: "タスクがありません",
    today: "今日やること",
    priority: "優先タスク",
  },
  dashboard: {
    title: "ダッシュボード",
    subtitle: "今日やること・承認待ち・コスト / 生産性",
    analyticsBanner: "ビジネスダッシュボード — AIコスト / 生産性 / エージェント活動",
    openAnalytics: "分析を開く",
    projects: "プロジェクト",
    tasks: "タスク",
    approvals: "承認",
    clients: "クライアント",
    leads: "リード",
    activeProjects: "進行中プロジェクト",
    aiActivity: "AI活動",
    aiActivityDesc: "最近の実行履歴",
    noExecutions: "秘書AIに相談すると履歴が表示されます",
    noApprovals: "承認待ちなし",
    noTodayTasks: "タスクがありません",
  },
  analytics: {
    title: "分析",
    subtitle: "ビジネスダッシュボード（コスト / 生産性 / AI活動）",
    aiCost: "AIコスト",
    tokenUsage: "トークン使用量",
    taskCompletion: "タスク完了率",
    artifacts: "成果物",
    agentActivity: "エージェント活動",
    agentActivityDesc: "エージェント別実行回数",
    recentCosts: "最近のコスト",
    noActivity: "実行履歴なし",
    noCosts: "LLM API利用時にコストが記録されます",
    records: "件",
    doneSuffix: "完了",
    tokens: "トークン",
  },
  agents: {
    title: "AIエージェント",
    subtitle: "開発チーム + ビジネス（全9エージェント）",
    orchestratorNote: "オーケストレーター — ワークフロー制御権限を持つ唯一のエージェント",
    noDirectComm: "エージェント間の直接通信は禁止。ワークフローエンジンが順番に実行します。",
    goWorkflows: "ワークフローへ",
    approvalLevel: "承認レベル",
  },
  artifacts: {
    title: "成果物",
    subtitle: "AIが生成した成果物（エージェント間の受け渡し媒体）",
    empty: "成果物がありません。ワークフローで「次のタスクを実行」を実行するとエージェントが成果物を生成します。",
    goProject: "プロジェクトへ",
    truncated: "...(省略)",
  },
  validation: {
    title: "検証",
    subtitle: "AI駆動の自動検証 — QAエージェントがシステム状態をチェックしレポートを生成",
    run: "自動検証を実行",
    running: "検証中...",
    includeWorkflow: "ワークフロー実行テストを含める（デモプロジェクトで次のタスクを実行・DB更新あり）",
    checkResults: "チェック結果",
    qaReport: "QAエージェントレポート",
    readOnly: "読み取り専用",
    executeMode: "実行モード",
    cliHint: "CLIからも実行可能",
    cliReadOnly: "読み取り専用",
    cliExecute: "ワークフロー実行テスト含む",
    networkError: "ネットワークエラーが発生しました",
    failed: "検証に失敗しました",
  },
  settings: {
    title: "設定",
    subtitle: "AI Workforce OS システム情報",
    application: "アプリケーション",
    version: "バージョン",
    phase: "フェーズ",
    phaseValue: "AI Workforce OS 完成版",
    llmMode: "LLMモード",
    apiConnected: "API接続済み",
    offlineFallback: "オフラインフォールバック",
    quickLinks: "クイックリンク",
    memoryLayers: "メモリ層",
    memoryDesc: "短期 · プロジェクト · ユーザー（グローバル / スキルは将来拡張）",
  },
  secretary: {
    title: "秘書AI",
    subtitle: "タスク整理・次のアクション提案",
    placeholder: "今日やることを相談...",
    submit: "秘書AIに相談",
    sending: "送信中...",
    error: "秘書AI応答に失敗しました",
    networkError: "通信エラーが発生しました",
  },
  feedback: {
    errorTitle: "実行エラー",
    taskDone: "タスク実行完了",
    taskReview: "ステータスが",
    taskReviewStatus: "レビュー中",
    taskDoneHint: "になりました。次を確認してください:",
    goApprovals: "承認",
    goApprovalsAction: "で承認",
    goArtifacts: "成果物",
    goArtifactsAction: "で成果物を確認",
    started: "ワークフローを開始しました。エージェント割当済み — 「次のタスクを実行」をクリックして最初のタスクを実行してください。",
    completed: "すべてのタスクが完了しました。ワークフローは",
    completedStatus: "完了",
    completedSuffix: "です。",
  },
  status: {
    draft: "下書き",
    active: "有効",
    completed: "完了",
    archived: "アーカイブ",
    todo: "未着手",
    running: "実行中",
    review: "レビュー中",
    done: "完了",
    blocked: "ブロック",
    pending: "保留",
    approved: "承認済み",
    rejected: "却下",
    critical: "緊急",
    high: "高",
    medium: "中",
    low: "低",
    pass: "合格",
    fail: "不合格",
    warn: "警告",
    skip: "スキップ",
    waiting_approval: "承認待ち",
    planning: "計画中",
    lead: "リード",
    inactive: "無効",
    email: "メール",
    meeting: "会議",
    phone: "電話",
    business: "ビジネス",
    development: "開発",
    cancelled: "キャンセル",
    failed: "失敗",
  },
} as const;

export type JaLabels = typeof ja;

export function tStatus(value: string): string {
  return (ja.status as Record<string, string>)[value] ?? value;
}
