export const ja = {
  nav: {
    dashboard: "ダッシュボード",
    analytics: "分析",
    projects: "プロジェクト",
    clients: "クライアント",
    tasks: "タスク",
    workflows: "ワークフロー",
    artifacts: "成果物",
    agents: "AIエージェント",
    approvals: "承認",
    validation: "検証",
    settings: "設定",
    completedProjects: "完了案件",
  },
  common: {
    back: "戻る",
    create: "作成",
    save: "保存",
    cancel: "キャンセル",
    loading: "処理中...",
    unassigned: "未割当",
    noData: "データがありません",
    openList: "一覧へ",
    project: "プロジェクト",
    workflow: "ワークフロー",
    task: "タスク",
    progress: "進捗",
    tasksDone: "件完了",
    updated: "更新",
    tasks: "タスク",
    comms: "連絡",
    projects: "案件",
  },
  workflow: {
    title: "ワークフロー",
    controls: "ワークフロー操作",
    controlsDesc: "秘書AI経由でエージェントを順番に実行",
    start: "ワークフロー開始",
    executeNext: "次のタスクを実行",
    startAndExecute: "開始して最初のタスクを実行",
    openWorkflow: "ワークフローを開く",
    noTasks: "タスクがありません",
    structure: "ワークフロー基本構造の可視化",
    automation: "自動化対応",
    workflowCount: "件のワークフロー",
  },
  approval: {
    title: "承認",
    subtitle: "Human in the Loop 承認管理",
    pending: "承認待ち",
    history: "履歴",
    noPending: "承認待ちはありません",
    approve: "承認する",
    reject: "却下する",
    commentPlaceholder: "コメント（任意）",
    goToList: "承認一覧へ",
  },
  client: {
    title: "クライアント",
    subtitle: "リード・クライアント管理と連絡履歴",
    leads: "リード",
    activeClients: "契約中クライアント",
    add: "クライアント追加",
    addAsLead: "リードとして追加",
    noClients: "クライアントがありません",
    activate: "クライアントを有効化する",
    namePlaceholder: "名前 *",
    companyPlaceholder: "会社名",
    emailPlaceholder: "メール",
    subjectPlaceholder: "件名",
    contentPlaceholder: "内容 *",
    businessProject: "制作プロジェクトを作成",
    businessProjectDesc: "クライアントに紐づく統合制作ワークフローを開始",
    createBusinessProject: "制作プロジェクトを作成",
    communications: "連絡履歴",
    addCommunication: "履歴を追加",
    noCommunications: "履歴なし",
    relatedProjects: "関連プロジェクト",
    projectName: "案件名",
    projectDesc: "案件概要",
  },
  project: {
    title: "プロジェクト",
    subtitle: "制作プロジェクトの作成と管理",
    devWorkflowNote:
      "営業 → 契約 → 要件 → デザイン → 開発 → QA → 法務 → 納品の統合ワークフローが自動作成されます。",
    new: "新規制作プロジェクト",
    templateLabel: "テンプレート",
    templateHint:
      "LP（静的）がデフォルトです。開発モードと詳細設定で工程を調整できます。",
    devModeLabel: "開発モード",
    devModeHint:
      "フロントエンド・バックエンド・外部開発・インフラをまとめて設定します。",
    devModeInternal: "AI内製（FE/BE を順に実行）",
    devModeExternal: "外部コーディング（Cursor 等 → 外部開発で登録）",
    devModeNone: "開発なし",
    devModeLinkedPreview: "連動する工程",
    devModeCustomWarning:
      "開発関連の工程が標準パターンと異なります。開発モードを選び直すと4工程をまとめて更新します。",
    stageModeAdvanced: "工程モードの詳細設定",
    stageModeAdvancedHint:
      "デザイン・営業〜納品を個別に変更できます。開発は上の開発モードで設定します。",
    stageModeSettings: "工程モード設定",
    stageModeSettingsDesc:
      "未着手の工程のみモードを変更できます。法務工程は変更不可です。",
    stageModeSave: "工程モードを保存",
    stageModeSaved: "工程モードを保存しました",
    stageModeLocked: "開始済み — 変更不可",
    executionMode: "実行モード",
    namePlaceholder: "プロジェクト名",
    descPlaceholder: "説明（任意）",
    addTask: "タスク追加",
    addTaskDesc:
      "選択した工程にタスクを追加します。工程ページで実行・承認されるタスクを設定できます。",
    addTaskStage: "追加先工程",
    taskName: "タスク名",
    taskCreate: "タスク作成",
    descLabel: "説明",
    workflowStructure: "基本構造（ステージ / タスク）",
    instruction: "案件への指示",
    instructionHint: "工程実行前に保存すると、次のAI実行時に参照されます。",
    instructionPlaceholder: "例: 今回は月額10万円の保守提案書を作成して",
    saveInstruction: "指示を保存",
    noActiveProject: "案件を選択",
    switchProject: "案件を切り替え",
    openProject: "この案件を開く",
    openWorkspace: "工程を進める",
    openSettings: "案件の設定",
    settingsSubtitle: "工程モード・タスク・ワークフロー構造の管理",
    viewDetails: "詳細を見る",
    noProjects: "進行中の案件がありません",
    thisProject: "この案件",
    globalSection: "全体",
    activeProjectSection: "工程ナビ",
    stageArtifacts: "成果物",
    stageArtifactsEmpty: "この工程の成果物はまだありません。",
    stagePrimaryAction: "次のアクション",
    stagePreviewLabel: "予定タスク",
    stageNoTasksAction:
      "この工程に実行可能なタスクがありません。プロジェクト設定を確認してください。",
    openProjectSettings: "プロジェクト設定を開く",
    openProjectDetails: "案件の詳細・設定へ",
    stageLockedTitle: "この工程はまだロックされています",
    stageLockedDescription:
      "前の工程を完了すると、この工程が解放されます。",
    stageReadOnly: "この工程は完了済みです。内容は成果物から確認できます。",
    stageNotFound: "指定された工程が見つかりません。",
    goPreviousStage: "前の工程へ戻る",
    markComplete: "案件を完了にする",
    markCompleteDesc: "のワークフローは終了しています。完了にすると専用一覧に移動します。",
    workflowDonePromptTitle: "ワークフロー完了",
    workflowDonePrompt:
      "全工程が終わりました。案件を完了にすると、ダッシュボードから完了一覧へ移動します。",
    viewCompletedProjects: "完了案件を見る",
  },
  completed: {
    title: "完了した案件",
    subtitle: "完了にした制作プロジェクトの参照一覧です。",
    empty: "完了した案件はまだありません。",
    viewLink: "完了案件を見る",
    completedAt: "完了日",
    markedComplete: "案件を完了にしました。",
  },
  task: {
    title: "タスク",
    subtitle: "タスク一覧と作成",
    add: "タスク追加",
    noTasks: "タスクがありません",
    today: "今日やること",
    priority: "優先タスク",
  },
  dashboard: {
    title: "Progress Popline",
    subtitle: "作業が流れるポップ工場 — 各案件の現在地と次のアクション",
    pipelineTitle: "ライブパイプライン",
    nowProcessing: "NOW PROCESSING",
    flowing: "流れてます",
    total: "TOTAL",
    activeProjectCount: "稼働案件",
    overallProgress: "全体進捗",
    advanceStep: "この工程を進める",
    startFirstStep: "最初の工程を進める",
    reviewContent: "内容を確認する",
    registerExternal: "外部成果物を登録",
    approveNow: "承認する",
    viewArtifacts: "成果物を見る",
    viewWorkflow: "ワークフロー詳細",
    goNextStage: "次の工程へ",
    createProject: "案件を作る",
    openWorkflowDetail: "詳細を開く",
    openApprovals: "承認一覧",
    completedProjects: "完了した案件",
    emptyTitle: "まだ案件がありません",
    emptyStep1: "① クライアントを追加",
    emptyStep2: "② 制作プロジェクトを作成",
    emptyStep3: "③ 案件を開いて工程を進める",
    ctaBusinessProject: "制作プロジェクトを作成",
    ctaDevProject: "プロジェクト一覧",
    ctaCreateProduction: "制作プロジェクトを作成",
    completedCountLink: "完了",
    pendingSummary: "承認待ちサマリー",
    stepDone: "DONE",
    stepRun: "RUN",
    stepWait: "WAIT",
    executedNotice: "工程を実行しました。「内容を確認する」から成果物を確認してください。",
    handoffNotice: "handoff 文書を生成しました。外部ツールで作業後、URLまたはファイルを登録してください。",
    registeredNotice: "外部成果物を登録しました。承認を進めてください。",
    approvedNotice: "承認しました。次の工程を進められます。",
    workflowDoneNotice:
      "ワークフローが完了しました。案件を完了にすると、完了一覧に移動します。",
    errorNotice: "実行エラー",
    analyticsBanner: "ビジネスダッシュボード — AIコスト / 生産性 / エージェント活動",
    openAnalytics: "分析を開く",
    projects: "プロジェクト",
    tasks: "タスク",
    approvals: "承認",
    clients: "クライアント",
    leads: "リード",
    activeProjects: "進行中プロジェクト",
    aiActivity: "AI活動",
    aiActivityDesc: "最近の実行履歴",
    noExecutions: "秘書AIに相談すると履歴が表示されます",
    noApprovals: "承認待ちなし",
    noTodayTasks: "タスクがありません",
  },
  analytics: {
    title: "分析",
    subtitle: "ビジネスダッシュボード（コスト / 生産性 / AI活動）",
    aiCost: "AIコスト",
    tokenUsage: "トークン使用量",
    taskCompletion: "タスク完了率",
    artifacts: "成果物",
    agentActivity: "エージェント活動",
    agentActivityDesc: "エージェント別実行回数",
    recentCosts: "最近のコスト",
    noActivity: "実行履歴なし",
    noCosts: "LLM API利用時にコストが記録されます",
    records: "件",
    doneSuffix: "完了",
    tokens: "トークン",
  },
  agents: {
    title: "AIエージェント",
    subtitle: "開発チーム + ビジネス（全9エージェント）",
    orchestratorNote: "オーケストレーター — ワークフロー制御権限を持つ唯一のエージェント",
    noDirectComm: "エージェント間の直接通信は禁止。ワークフローエンジンが順番に実行します。",
    goWorkflows: "案件の工程へ",
    approvalLevel: "承認レベル",
  },
  artifacts: {
    title: "成果物",
    subtitle: "AIが生成した成果物（エージェント間の受け渡し媒体）",
    empty: "成果物がありません。ワークフローで「次のタスクを実行」を実行するとエージェントが成果物を生成します。",
    goProject: "プロジェクトへ",
    truncated: "...(省略)",
    viewDetail: "詳細を見る",
    detailMeta: "成果物情報",
    detailContent: "本文",
    reviewBeforeApprove: "内容を確認のうえ、承認または却下してください。",
    backToDashboard: "ダッシュボードへ戻る",
    backToStage: "工程ページへ戻る",
    noPendingApproval: "この成果物に対する承認待ちはありません。",
    createdAt: "作成日時",
    registerExternal: "外部成果物を登録",
    registerExternalDesc:
      "Figma / GitHub / 本番 URL、または PDF・PNG 等のファイルを登録してください。",
    externalUrl: "URL（任意）",
    externalFile: "ファイル（任意）",
    externalNote: "メモ（任意）",
    externalNotePlaceholder: "補足説明（任意）",
    registerHint: "URL とファイルのどちらか一方は必須です。",
    registerSubmit: "登録して承認へ進む",
  },
  validation: {
    title: "検証",
    subtitle: "AI駆動の自動検証 — QAエージェントがシステム状態をチェックしレポートを生成",
    run: "自動検証を実行",
    running: "検証中...",
    includeWorkflow: "ワークフロー実行テストを含める（デモプロジェクトで次のタスクを実行・DB更新あり）",
    checkResults: "チェック結果",
    qaReport: "QAエージェントレポート",
    readOnly: "読み取り専用",
    executeMode: "実行モード",
    cliHint: "CLIからも実行可能",
    cliReadOnly: "読み取り専用",
    cliExecute: "ワークフロー実行テスト含む",
    networkError: "ネットワークエラーが発生しました",
    failed: "検証に失敗しました",
  },
  settings: {
    title: "設定",
    subtitle: "AI Workforce OS システム情報",
    application: "アプリケーション",
    version: "バージョン",
    phase: "フェーズ",
    phaseValue: "AI Workforce OS 完成版",
    llmMode: "LLMモード",
    apiConnected: "API接続済み",
    offlineFallback: "オフラインフォールバック",
    quickLinks: "クイックリンク",
    memoryLayers: "メモリ層",
    memoryDesc: "短期 · プロジェクト · ユーザー（グローバル / スキルは将来拡張）",
  },
  secretary: {
    title: "秘書AI",
    consultButton: "相談",
    fabLabel: "秘書AIを開く",
    closeDrawer: "秘書AIを閉じる",
    subtitle: "タスク整理・次のアクション提案",
    instructionHint:
      "工程の具体的な指示は、各案件カードの「指示を保存」が確実です。秘書AIは相談・整理用です。",
    placeholder: "今日やることを相談...",
    submit: "秘書AIに相談",
    sending: "送信中...",
    error: "秘書AI応答に失敗しました",
    networkError: "通信エラーが発生しました",
  },
  a11y: {
    skipToMain: "メインコンテンツへスキップ",
    search: "検索",
    notifications: "通知",
  },
  feedback: {
    errorTitle: "実行エラー",
    taskDone: "タスク実行完了",
    taskReview: "ステータスが",
    taskReviewStatus: "レビュー中",
    taskDoneHint: "になりました。次を確認してください:",
    goApprovals: "承認",
    goApprovalsAction: "で承認",
    goArtifacts: "成果物",
    goArtifactsAction: "で成果物を確認",
    started: "ワークフローを開始しました。エージェント割当済み — 「次のタスクを実行」をクリックして最初のタスクを実行してください。",
    completed: "すべてのタスクが完了しました。ワークフローは",
    completedStatus: "完了",
    completedSuffix: "です。",
  },
  status: {
    draft: "下書き",
    active: "有効",
    completed: "完了",
    archived: "アーカイブ",
    todo: "未着手",
    running: "実行中",
    review: "レビュー中",
    done: "完了",
    blocked: "ブロック",
    pending: "保留",
    approved: "承認済み",
    rejected: "却下",
    critical: "緊急",
    high: "高",
    medium: "中",
    low: "低",
    pass: "合格",
    fail: "不合格",
    warn: "警告",
    human_handoff: "人間デザイナー",
    skip: "スキップ",
    internal_ai: "AI内製",
    external_handoff: "外部ツール",
    waiting_approval: "承認待ち",
    waiting_external: "外部登録待ち",
    planning: "計画中",
    lead: "リード",
    inactive: "無効",
    email: "メール",
    meeting: "会議",
    phone: "電話",
    business: "ビジネス",
    development: "開発",
    production: "制作",
    lp_static: "LP（静的）",
    lp_form: "LP（フォーム）",
    corporate: "コーポレート",
    design_only: "デザインのみ",
    custom_blank: "カスタム",
    cancelled: "キャンセル",
    failed: "失敗",
  },
} as const;

export type JaLabels = typeof ja;

export function tStatus(value: string): string {
  return (ja.status as Record<string, string>)[value] ?? value;
}
